---
title: "Class10"
author: "Chen-Chia Ku"
date: "2023-11-15"
output:
  md_document:
    variant: markdown_github
  pdf_document:
    toc_depth: 5
    keep_tex: no 
    latex_engine: xelatex 
  html_document:
    toc_depth: '3'
    df_print: paged
  rmdformats::readthedown:
    css: custom.css
    self_contained: yes
    thumbnails: no
    lightbox: yes
    gallery: yes
    highlight: tango
    toc_depth: 3
header-includes:
- \usepackage{fontspec} 
- \usepackage{xeCJK}    
- \setCJKmainfont{標楷體}
- \usepackage{enumitem}
- \setlistdepth{15}
- \renewlist{itemize}{itemize}{15}
- \renewlist{enumerate}{enumerate}{15}
- \setlist[itemize]{label=$\cdot$}
- \setlist[itemize,1]{label=\textbullet}
- \setlist[itemize,2]{label=--}
- \setlist[itemize,3]{label=*}
editor_options:
  chunk_output_type: console
---
# **Class 10: Data Visualization, ggplot2**

# 1. Into the basic plotting under ggplot()

## 1.1. Library
```{r message=FALSE, warning=FALSE}
#install.packages("ggplot2")
library(ggplot2)

```

```{r include=FALSE}
library(showtext)
showtext_auto()
```

## 1.2. Read data
```{r}
Excerdt3 <- read.csv("E:/Drive/2_lab/Edu5_Course/R_MyFirstLesson/R/10_DataVisualize_ggplot2/Attachment/Excerdt3.csv")

```

## 1.3. Histogram

```{r message=FALSE, warning=FALSE, out.width="80%"}
ggplot()+
  geom_histogram(data=Excerdt3, mapping=aes(x=Precip_value))

#change the color
ggplot()+
  geom_histogram(data=Excerdt3, mapping=aes(x=Precip_value), color="black")

#extract different color
ggplot()+
  geom_histogram(data=Excerdt3, mapping=aes(x=Precip_value), color="black", fill="#144D69")

#Add x lab and y lab
ggplot()+
  geom_histogram(data=Excerdt3, mapping=aes(x=Precip_value), color="black", fill="#144D69")+
  xlab("Precipitation (mm)")+
  ylab("frequency")+
  ggtitle("Frequency of precipitation")

# YOU can give this plot a name
His <- ggplot()+
  geom_histogram(data=Excerdt3, mapping=aes(x=Precip_value), color="black", fill="#144D69")+
  xlab("Precipitation (mm)")+
  ylab("frequency")+
  ggtitle("Frequency of precipitation")

```

## 1.4. Density plot
histograms use bars and density use lines to present the frequency.
```{r message=FALSE, warning=FALSE, out.width="80%"}
ggplot()+
  geom_density(data=Excerdt3, mapping=aes(x=Precip_value), color="black", fill="#144D69")

# make the different color into different station
ggplot()+
  geom_density(data=Excerdt3, mapping=aes(x=Precip_value, fill=stationName), color="black")

ggplot()+
  geom_density(data=Excerdt3, mapping=aes(x=Precip_value, fill=stationName), color="black", alpha=0.3)

ggplot()+
  geom_density(data=Excerdt3, mapping=aes(x=Precip_value, fill=stationName), color="black", alpha=0.3)+
  xlab("Precipitation (mm)")+
  ylab("frequency")+
  ggtitle("Frequency of precipitation")

```

## 1.5. Bar plot

```{r message=FALSE, warning=FALSE, out.width="80%"}
ggplot()+
  geom_col(Excerdt3, mapping=aes(x=stationName, y=Precip_value))

ggplot(Excerdt3,aes(x=stationName, y=Precip_value))+
  geom_col()

```

### 1.5.1. change the bar position

```{r message=FALSE, warning=FALSE, out.width="80%"}
ggplot(Excerdt3,aes(x=stationName, y=Precip_value))+
  geom_col(fill="grey50", color="black")

ggplot(Excerdt3, aes(x=stationName, y=Precip_value, fill=as.factor(Y)))+
  geom_col(color="black")

ggplot(Excerdt3, aes(x=stationName, y=Precip_value, fill=as.factor(Y)))+
  geom_col(color="black", position = "dodge")
ggplot(Excerdt3, aes(x=stationName, y=Precip_value, fill=as.factor(Y)))+
  geom_col(color="black", position = "stack")
ggplot(Excerdt3, aes(x=stationName, y=Precip_value, fill=as.factor(Y)))+
  geom_col(color="black", position = "fill")
```

### 1.5.2. Change the color 
```{r message=FALSE, warning=FALSE, out.width="80%"}
ggplot(Excerdt3, aes(x=stationName, y=Precip_value, fill=as.factor(Y)))+
  geom_col(color="black", position = "dodge")+
  scale_fill_manual(name="Year", values=c("red", "blue", "yellow", "grey50", "black"))

ggplot(Excerdt3, aes(x=stationName, y=Precip_value, fill=as.factor(Y)))+
  geom_col(color="black", position = "dodge")+
  scale_fill_manual(name="Year", values=c("#153049", "#385487", "#25A184", "#A9D13F", "#F3E949", "#FAF6B3"))

```

### 1.5.3. Use the color palette
```{r message=FALSE, warning=FALSE, out.width="80%"}

mypal <- colorRampPalette(c("#153049","#443A83","#287D8E","#25AB82","#98CC48","#F0E51D","#f5ed67","#FAF6B3"))

```

```{r message=FALSE, warning=FALSE, out.width="80%"}
ggplot(Excerdt3, aes(x=stationName, y=Precip_value, fill=as.factor(Y)))+
  geom_col(color="black", position = "dodge")+
  scale_fill_manual(name="Year", values=mypal(10))# change the value of the palette

ggplot(Excerdt3, aes(x=stationName, y=Precip_value, fill=as.factor(Y)))+
  geom_col(color="black", position = "dodge")+
  scale_fill_manual(name="Year", values=mypal(10))+
  xlab("station")+
  ylab("precipitation(mm)")

Bar <- ggplot(Excerdt3, aes(x=stationName, y=Precip_value, fill=as.factor(Y)))+
  geom_col(color="black", position = "dodge")+
  scale_fill_manual(name="Year", values=mypal(10))+
  xlab("station")+
  ylab("precipitation(mm)")


```


## 1.6. Point
```{r message=FALSE, warning=FALSE, out.width="80%"}
ggplot(Excerdt3, aes(x=averageT_value, y=Precip_value))+
  geom_point()

ggplot(Excerdt3, aes(x=averageT_value, y=Precip_value))+
  geom_point()+
  xlab(expression("Temperature " (degree*C)))+
  ylab("precipitation(mm)")


```

### 1.6.1 scaling the axis
```{r message=FALSE, warning=FALSE, out.width="80%"}
ggplot(Excerdt3, aes(x=averageT_value, y=Precip_value))+
  geom_point()+
  
  scale_x_continuous(limits = c(0,30))+
  scale_y_continuous(limits= c(0, 6000))+
  
  xlab(expression("Temperature " (degree*C)))+
  ylab("precipitation(mm)")

ggplot(Excerdt3, aes(x=averageT_value, y=Precip_value))+
  geom_point()+
  
  scale_x_continuous(limits = c(0,30), breaks = c(0,5, 10,15, 20, 25,30))+
  scale_y_continuous(limits= c(0, 6000), breaks=c(0, 1000,2000, 3000, 4000, 5000, 6000))+
  
  xlab(expression("Temperature " (degree*C)))+
  ylab("precipitation(mm)")

ggplot(Excerdt3, aes(x=averageT_value, y=Precip_value))+
  geom_point()+
  
  scale_x_continuous(limits = c(0,30), 
                     breaks = seq(0,30, by=10))+
  scale_y_continuous(limits= c(0, 6000), 
                     breaks=seq(0, 6000, by=100))+
  
  xlab(expression("Temperature " (degree*C)))+
  ylab("precipitation(mm)")

ggplot(Excerdt3, aes(x=averageT_value, y=Precip_value))+
  geom_point()+
  
  scale_x_continuous(limits = c(0,30), 
                     breaks = seq(0,30, by=10), 
                     labels=seq(0, 3, by=1))+
  scale_y_continuous(limits= c(0, 6000), 
                     breaks=seq(0, 6000, by=1500))+
  
  xlab(expression("Temperature " (degree*C)))+
  ylab("precipitation(mm)")

Pointplot <- ggplot(Excerdt3, aes(x=averageT_value, y=Precip_value))+
  geom_point()+
  
  scale_x_continuous(limits = c(0,30), 
                     breaks = seq(0,30, by=10), 
                     labels=seq(0, 3, by=1))+
  scale_y_continuous(limits= c(0, 6000), 
                     breaks=seq(0, 6000, by=1500))+
  
  xlab(expression("Temperature " (degree*C)))+
  ylab("precipitation(mm)")

```



# 2. save the plot

```{r  message=FALSE, warning=FALSE, out.width="80%"}
# Export the graph
ggsave(Pointplot,filename = "Excercise_output/Pointplot_gsave.png",  width = 10, height=10, units="cm", dpi=300)

```

```{r message=FALSE, warning=FALSE, out.width="80%"}
library(ggpubr) #install.packages("ggpubr")

ggexport(Pointplot, filename = "Excercise_output/Pointplot_gexport.png", width=3000, height=3000, res=1500)
```
